# Generated by Django 3.1.4 on 2020-12-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stagg',
            new_name='is_stuff',
        ),
    ]
