# Generated by Django 3.1.4 on 2021-02-05 11:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_side',
            new_name='image_side_left',
        ),
        migrations.AddField(
            model_name='product',
            name='image_side_right',
            field=models.ImageField(default='/pic/left/', upload_to=core.models.product_image_file_path),
            preserve_default=False,
        ),
    ]
