# Generated by Django 3.1.4 on 2021-01-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAppend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order_item_append_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderitemappendcategory')),
            ],
        ),
    ]
