# Generated by Django 3.1.4 on 2021-02-11 15:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210205_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_image',
            field=models.ImageField(default='/test/', upload_to=core.models.design_image_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image_back',
            field=models.ImageField(default='/test/', upload_to=core.models.design_image_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image_side_left',
            field=models.ImageField(default='/left/', upload_to=core.models.design_image_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image_side_right',
            field=models.ImageField(default='/right/', upload_to=core.models.design_image_file_path),
            preserve_default=False,
        ),
    ]
