# Generated by Django 3.1.4 on 2021-03-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210219_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='final_image',
            new_name='final_product_image_back',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_image_back',
            new_name='final_product_image_front',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_image_front',
            new_name='final_product_image_side_left',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_image_side_left',
            new_name='final_product_image_side_right',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image_side_right',
        ),
    ]
