# Generated by Django 3.1.4 on 2021-01-23 18:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitemappend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, default='Tehran Azadi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, default=3750363511, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, default='Is the best in market', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='/upload/recipe/', upload_to=core.models.product_image_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, default='note', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rainking',
            field=models.FloatField(blank=True, default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.IntegerField(blank=True, default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='units_on_order_per_day',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_gram',
            field=models.FloatField(blank=True, default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_type',
            field=models.CharField(blank=True, default='percent', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='url',
            field=models.URLField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
