# Generated by Django 3.1.4 on 2021-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=27, max_length=3),
            preserve_default=False,
        ),
    ]
