# Generated by Django 3.1.4 on 2021-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210107_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='discount_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
