# Generated by Django 3.1.4 on 2021-02-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
