# Generated by Django 3.1.4 on 2021-01-07 12:27

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='No colore', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.FloatField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='Iran', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Tshirt', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rainking',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='larg', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units_on_order_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.FloatField(null=True),
        ),
    ]
