# Generated by Django 3.1.4 on 2021-01-23 18:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210123_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to=core.models.product_image_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rainking',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_on_order_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_gram',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
