# Generated by Django 3.1.4 on 2021-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210107_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
