# Generated by Django 3.1.4 on 2021-01-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210107_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight_kg',
            new_name='weight_gram',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='No color', max_length=64),
        ),
    ]
