# Generated by Django 3.1.4 on 2021-01-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210122_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemCategoryAppend',
            new_name='OrderItemAppendCategory',
        ),
    ]
