# Generated by Django 3.1.4 on 2021-01-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210122_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='Tshirt', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitemappendcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
