# Generated by Django 3.1.4 on 2021-01-23 20:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210123_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/vol/web/media/uploads/product/test.jpg', null=True, upload_to=core.models.product_image_file_path),
        ),
    ]
