# Generated by Django 3.1.4 on 2021-01-24 11:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210123_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemappend',
            name='image',
            field=models.ImageField(default='uploads/orderitemappend/', upload_to=core.models.order_item_append_image_file_path),
            preserve_default=False,
        ),
    ]
