# Generated by Django 3.1.4 on 2021-01-24 11:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderitemappend_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/Null/', upload_to=core.models.product_image_file_path),
            preserve_default=False,
        ),
    ]
