# Generated by Django 3.1.4 on 2021-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210124_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemappend',
            name='order_item_append_price_irr',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
