# Generated by Django 3.1.4 on 2021-01-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitemappend_order_item_append_price_irr'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_brand', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=64)),
                ('product_description', models.CharField(max_length=512, null=True)),
                ('price_irr', models.IntegerField()),
                ('total', models.IntegerField()),
                ('discount', models.FloatField(default=0.0)),
                ('size', models.CharField(max_length=64)),
                ('color', models.CharField(default='No color', max_length=64)),
                ('weight_gram', models.FloatField(null=True)),
                ('product_image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='orderitemappend',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.orderitem'),
            preserve_default=False,
        ),
    ]
