# Generated by Django 3.1.4 on 2021-01-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210126_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='total_price_irr',
        ),
    ]
