# Generated by Django 3.1.4 on 2021-01-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210126_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemappend',
            name='order_item',
        ),
    ]
